on: [workflow_dispatch, repository_dispatch]

jobs:
  cypress-run:
    name: Cypress Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          ${{ github.workspace }}/.next/cache
      # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
      # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}- 

    - name: Cypress run
      uses: cypress-io/github-action@v5
      env:
        NEXT_PUBLIC_HASURA_REST_API: ${{ secrets.NEXT_PUBLIC_HASURA_REST_API }}
        NEXT_PUBLIC_CMS_REST_API: ${{ secrets.NEXT_PUBLIC_CMS_REST_API }}
      with:
        build: npm run build
        start: npm start
  
  build-deploy:
    name: Build & Deploy
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Install Vercel
      run: npm i -g vercel
    
    - name: Link to Vercel project with Token & Scope
      run: vercel link --scope roger-urich --token ${{ secrets.VERCEL_TOKEN }} --yes
      
    - name: Build & Deploy to Vercel
      run: vercel --token ${{ secrets.VERCEL_TOKEN }}