name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          NEXT_PUBLIC_HASURA_REST_API: https://hasura.rurich.dev/api/rest
          NEXT_PUBLIC_CMS_REST_API: https://cms.rurich.dev/api
        with:
          build: npm run build
          start: npm start
