on:
  push:
    branches-ignore:
      - main

jobs:
  cypress-run:
    name: Cypress Test
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Lint
        run: npm run lint

      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          NEXT_PUBLIC_HASURA_REST_API: ${{ secrets.NEXT_PUBLIC_HASURA_REST_API }}
          NEXT_PUBLIC_CMS_REST_API: ${{ secrets.NEXT_PUBLIC_CMS_REST_API }}
        with:
          build: npm run build
          start: npm start